### ISSUE TITLE
Delete task is broken.

### ISSUE THREAD

**Issue by mattloose** [LooseLab/minotourapp#127]
The delete task is currently broken.

**Comment by mattloose** [comment]
Running the flowcell delete task code manually runs correctly. Therefore I think it is something to do with the way that the task is set.

**Comment by mattloose** [comment]
@py5gol @Adoni5 

I've added a clunky fix on develop for this - specifically issue is that the delete task was receiving an empty reference and so failing because it couldn't find a match.

**Comment by Adoni5** [comment]
just tested - delete flowcell is fully functioning - fixed in course of closing #147
