### ISSUE TITLE
MinKNOW control page still mentions pore history chart

### ISSUE THREAD

**Issue by alexomics** [LooseLab/minotourapp#142]
Last paragraph on the MinKNOW control page mentions a pore history chart that _may_ have moved to the live data tab.  
> The pore history chart is only updated every 5 minutes to reduce page loading times.

**Comment by Adoni5** [comment]
Deleted this line
https://github.com/LooseLab/minotourapp/blob/d2259eb37c05a460b4e9a88b502be14d66870894/web/templates/web/remotecontrol.html#L30
