### ISSUE TITLE
Share access to flowcells with other users

### ISSUE THREAD

**Issue by py5gol** [LooseLab/minotourapp#156]
Currently, users can not share information about their flowcells with other users. This feature should let users invite other users registered in the system to view the flowcell details (read only mode) or start new analysis (read write mode). In any case, only flowcell owners are allowed to delete a flowcell.

**Comment by Adoni5** [comment]
This is done. A couple of issues which may be fixed just vis a vis admin account, but closing this as main listed requests are resolved.
