### ISSUE TITLE
Flowcell activation fails

### ISSUE THREAD

**Issue by mattloose** [LooseLab/minotourapp#162]
**Describe
There is no way to reactivate a flowcell. Flowcell data addition does not reactivate it. Admin doesn’t allow it. 

Runs can be longer than 48 hours. 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
New data should trigger the flowcell to be active. Addition of a new run should set the flowcell to be active. Addition of a new task should activate flowcell. 

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other notes about the bug here.

**Comment by Adoni5** [comment]
The flowcell now switches to active after a new run is added to the flowcell. It stays active for 7 days. Added the code to the Reads/views.py run_list function.
