### ISSUE TITLE
Default flowcell active time too short. 

### ISSUE THREAD

**Issue by mattloose** [LooseLab/minotourapp#163]
**Describe the bug**
Default active flowcell time is 48 hours. This is too short and causes runs to stop processing early. 

**To Reproduce**
Steps to reproduce the behaviour:
Create new flowcell. 
Wait 48 hours. 

**Expected behaviour**
Default flowcell active time should be seven days. 

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other notes about the bug here.

**Comment by Adoni5** [comment]
Changed default active time length to 7 days. Added button on tasks tabs to manually reactivate a flowcell. Relevant to issue #162 .
