### ISSUE TITLE
Flowcell size update fails on admin created flowcells. 

### ISSUE THREAD

**Issue by mattloose** [LooseLab/minotourapp#164]
**Describe the bug**
Admin created flowcells don’t update the channel counts correctly. 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Need a way to create the appropriate tasks for a flowcell. 

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other notes about the bug here.

**Comment by Adoni5** [comment]
The created flowcell had a run added to it, which works fine for most tasks. However UpdateFlowcellDetails queries the FastQRead objects in the database by using the Flowcell as a lookup. All the FastQReads attached to the run we moved across still have the old flowcell set in their flowcell field, so the query returns no fastQ objects and therefore we have no max channel size. 

Fixing this we could do the max channel size using the runs, or reset the fastq flowcell. Something tells me this isn't the way to go though? Should it not point to the Flowcell they were made with? Also if you are creating through the admin interface is there even a way to reverse update the FastQRead Flowcell field?

**Comment by Adoni5** [comment]
@py5gol - as we discussed

**Comment by Adoni5** [comment]
Closing as this now falls under @py5gol Flowcell Splitting issue on the Dev Azure board
