### ISSUE TITLE
Sharee shouldn't be able to share a flowcell

### ISSUE THREAD

**Issue by Adoni5** [LooseLab/minotourapp#177]
**Describe the bug**
A user who has a flowcell shared with them is able to share that flowcell further

**To Reproduce**
Steps to reproduce the behaviour:
Share a flowcell with someone, log in as that person, share the flowcell

**Expected behaviour**
Not allowed ever?

**Desktop (please complete the following information):**
 - Ubuntu 16.04 
 - Firefox 64bit
 -  68.0.2

**Comment by Adoni5** [comment]
Should a sharee also be able to see who else a flowcell is shared with, as this is currently the case

**Comment by py5gol** [comment]
Investigating https://django-guardian.readthedocs.io/en/stable/userguide/assign.html. This library extends the django's permission system allowing permissions on object level.

**Comment by Adoni5** [comment]
Checked this and the main issue is fixed, and we're cool with the sharers all being in the know!
