### ISSUE TITLE
Archive a flowcell, deleting a Fastq but keeping summaries

### ISSUE THREAD

**Issue by Adoni5** [LooseLab/minotourapp#182]
**Is your feature request related to a problem in existing functionality or a lack thereof? Please describe.**
We anticipate a build up of fastq data on the server that will be sat there untouched for decades. Without a way to remove the fastq data and keep the flowcell and summaries, we are stuck

**Describe the solution you'd like.**
- Task that runs every day to check if the flowcell has been inactive for 30 days. If it has "Archive the flowcell", clearing a lot of the data. We could also just do it 30 days dead after the flowcell creation.

**Comment by Adoni5** [comment]
Update - The task should be absolute, so any data whether in an active or inactive flowcell should be deleted after 21 days, and it should include the PafStore entries for that flowcell but keep the summaries.

**Comment by mattloose** [comment]
Further update... should be sitewide configurable. So deadline could be configured in site settings - e.g number_of_days_before_archive = 21 or could be set to 150 etc.  etc etc.

**Comment by Adoni5** [comment]
#169 is very similar to this, without the archive aspect. Will make one function with flag. Will also require the user to verify intent, same as delete when starting the task.

**Comment by Adoni5** [comment]
Completed in commit f68e9871
