### ISSUE TITLE
Proxies ?

### ISSUE THREAD

**Issue by colindaven** [LooseLab/minotourapp#183]
Hi,

interesting project. Have you had good experience with users getting their data through university proxies ?

Also, if I want to minimize data volumes and have to keep sensitive data onsite (in some projects), so are any sequence data sent ? Ideally I just want to see minion stats from remote during the run, and maybe some "LIMS" functionality to compare this to previous runs.

Thanks
Colin

**Comment by mattloose** [comment]
Hi Colin,

Thanks for the feedback. 

So everything is handled over an api on standard ports. If you can see the website then you should be able to connect through a proxy. 

Our long term goal for this project is not to host everyone’s data - but for users to set up there own instances of it becomes useful to them. Hence we have built a django back end and the system can be deployed via docker on a local system relatively easily. Future plans include allowing users to send data from one instance of Minotour to another - so collect data in field and then collate it all back to one location as an example. 

With respect to sending sequence data. This is entirely at the uploaders control. We conceptually divide ‘live’ data from ‘base called’ data. Live data is equivalent to the metrics that Minknow reports during a run and so contains no sequence data. 

Base called data is reading information from the fastq data themselves. Here users have the option of uploading information about a sequence (but no actual sequence data) or uploading sequence data as well. If you upload sequence data there are options for mapping or centrifuging data as things you can do. We hope that down the line individuals may develop there own analyses to go in. 

So in your case the most straightforward option would be to monitor ‘live’ data only. This (barring a couple of minor issues we are resolving) is a simple case of running the data uploaded in the background whilst runs are on. You don’t have to think much more about it than that. 

Hope this helps. 

Matt
