### ISSUE TITLE
AttributeError: 'JobMaster' object has no attribute 'paf_store_list'

### ISSUE THREAD

**Issue by py5gol** [LooseLab/minotourapp#189]
The error message below appears when I tried to delete a minimap2 task.

celery_worker    | [2019-10-18 14:48:05,882: ERROR/ForkPoolWorker-2] Task web.delete_tasks.delete_alignment_task[707c10a9-3b52-4d46-9b7d-426ad078c958] raised unexpected: AttributeError("'JobMaster' object has no attribute 'paf_store_list'",)
celery_worker    | Traceback (most recent call last):
celery_worker    |   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 385, in trace_task
celery_worker    |     R = retval = fun(*args, **kwargs)
celery_worker    |   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 648, in __protected_call__
celery_worker    |     return self.run(*args, **kwargs)
celery_worker    |   File "/var/lib/minotour/apps/minotourapp/web/delete_tasks.py", line 80, in delete_alignment_task
celery_worker    |     delete_rows(first_pafstore_row, 1000, flowcell_job, "paf_store_list")
celery_worker    |   File "/var/lib/minotour/apps/minotourapp/web/delete_tasks.py", line 26, in delete_rows
celery_worker    |     affected = getattr(job_master_object, reverse_lookup).filter(pk__lte=last_row_to_be_deleted).delete()
celery_worker    | AttributeError: 'JobMaster' object has no attribute 'paf_store_list'

**Comment by Adoni5** [comment]
This is fixed, that was a typo
