### ISSUE TITLE
Chancalc task does not update the last read attribute

### ISSUE THREAD

**Issue by py5gol** [LooseLab/minotourapp#190]
**Describe the bug**
Please provide a clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other notes about the bug here.

**Comment by Adoni5** [comment]
This is fixed.
