### ISSUE TITLE
Download CSV from live data is broken

### ISSUE THREAD

**Issue by mattloose** [LooseLab/minotourapp#231]
**Describe the bug**
Attempting to download CSV from a live run report is broken - error message

KeyError at /web/private/flowcells/39/flowcell_run_stats_csv/
"['minION_id'] not found in axis"

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other notes about the bug here.

**Comment by Adoni5** [comment]
Fixed in commit 9880a0a
