### ISSUE TITLE
References for ARTIC pipelines must only contain a single sequence.

### ISSUE THREAD

**Issue by mattloose** [LooseLab/minotourapp#306]
**Describe the bug**
When running the artic pipeline, a reference file must only contain a single sequence. This is a requirement of the artic pipeline, BUT some of the ARTIC primer schemes incorrectly provide multi sequence references.
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other notes about the bug here.

**Comment by Adoni5** [comment]
fixed in c2b4ab52

**Comment by Adoni5** [comment]
Added checks to not allow upload of references for primer scheme with multiple sequences
