### ISSUE TITLE
Deleting a reference only removes the database entries.

### ISSUE THREAD

**Issue by mattloose** [LooseLab/minotourapp#307]
**Describe the bug**
When deleting a reference through the GUI, only the database entries are removed and not the reference files themselves?

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other notes about the bug here.

**Comment by Adoni5** [comment]
Fixed in cb38f32b
