### ISSUE TITLE
Read Length Filter

### ISSUE THREAD

**Issue by mattloose** [LooseLab/minotourapp#308]
**Describe the bug**
The read length filter cannot be a global property for artic - it should be set alongside the artic scheme.
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Desktop (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
Add any other notes about the bug here.

**Comment by Adoni5** [comment]
Fixed in 25c34151
