### ISSUE TITLE
Multiple devices not showing on Minknow view? 

### ISSUE THREAD

**Issue by adbeggs** [LooseLab/minotourapp#336]
Hi all

May be missing something but we have multiple machines (2xgrid 1xprom) uploading to Minotaur. Can see all machines and flowcells in the "Flowcell" view but only the one computer says it is connected on the Minknow control view... Am I missing something here???

**Comment by Adoni5** [comment]
Hey Andrew,

I'm really sorry about the slow reply! I have an idea what may have been going on here but I need a little more information! 

First off if you know (or can remember), were the minFQ instances uploading the data definitely connected? And not run with the`-nm` no minknow flag?

Also do you know which Sequencer was showing up? Was it by any chance the PromethION?

Apologies again,

Rory

**Comment by adbeggs** [comment]
Hi Rory

Problem solved – it was a Grid but it was intermittently dropping its fixed network connection due to a software issue.

Is fixed now and is showing

BW

Andrew
