### ISSUE TITLE
Problems with the graphical user interface

### ISSUE THREAD

**Issue by lhoffmann97** [LooseLab/minotourapp#345]
I have a problem with the graphical user interface. I used the Docker solution to install minoTour. I´ve also created an account - a normal user as well as an admin - but it is just possible for me to login in minoTour from the computer where I´ve installed the normal user and the admin. I cannot login in minoTour from another computer although the installation of the other computer was succesful.

**Comment by Adoni5** [comment]
Hi @lhoffmann97 , apologies for the slow reply, I've been on placement elsewhere. I'm not sure I fully understand the issue - It is possible to login to minoTour over the network. but the computer/server that is running minoTour needs to be correctly configured for networking. If you don't manage the computer/server, you may have to talk to your IT department about this.

If the computer has an open port for minoTour to be hosted on, the configuration file (in the docker repo) is `minotourapp_nginx.conf`. The comments in that file should be able to guide you. 

I'll close this issue for now, but feel free to re open if you need more help.
